name: Deploy Extension
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
      VS_MARKETPLACE_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install
        run: bun install --frozen-lockfile && cd media-src && bun install --frozen-lockfile
      - name: Build
        run: bun ./build.ts
      - name: Test
        run: bun run test
      - name: Publish to Open VSX Registry
        if: env.OPEN_VSX_TOKEN != ''
        uses: HaaLeo/publish-vscode-extension@v0
        id: publishToOpenVSX
        with:
          pat: ${{ env.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        if: env.VS_MARKETPLACE_TOKEN != ''
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ env.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
